version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: kevin12345
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - /custom/mount:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped